apiVersion: apps/v1
kind: Deployment

metadata:
  name: admin-server
  namespace: petclinic

spec:
  replicas: 1

  selector:
    matchLabels:
      app: admin-server

  template:
    metadata:
      labels:
        app: admin-server

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: admin-server
          image: 524338476341.dkr.ecr.eu-central-1.amazonaws.com/petclinic-admin-server:4.0.1
          imagePullPolicy: Always

          ports:
            - containerPort: 9090

          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 120
            periodSeconds: 20
