apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: petclinic
  labels:
    app.kubernetes.io/name: config-server
    app.kubernetes.io/part-of: petclinic
spec:
  replicas: 1

  selector:
    matchLabels:
      app: config-server

  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: config-server
        app.kubernetes.io/name: config-server
        app.kubernetes.io/part-of: petclinic

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: config-server
          image: 524338476341.dkr.ecr.eu-central-1.amazonaws.com/petclinic-config-server:4.0.2

          imagePullPolicy: Always

          ports:
            - containerPort: 8888

          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 120
            periodSeconds: 20
